create view importcedr.v_operacniprogram as select idoperacniprogram as id, operacniprogramkod as kod, operacniprogramnazev as nazev from importcedr.ciselnikmmroperacniprogramv01 union select idoperacniprogram as id, operacniprogramkod as kod, operacniprogramnazev as nazev from importcedr.ciselnikcedroperacniprogramv01;
create view importcedr.v_priorita as select idpriorita as id, prioritakod as kod, prioritanazev as nazev from importcedr.ciselnikcedrprioritav01 union select idpriorita as id, prioritakod as kod, prioritanazev as nazev from importcedr.ciselnikmmrprioritav01;
create view importcedr.v_grantoveschema as select idgrantoveschema as id, grantoveschemakod as kod, grantoveschemanazev as nazev from importcedr.ciselnikcedrgrantoveschemav01 union select idgrantoveschema as id, grantoveschemakod as kod, grantoveschemanazev as nazev from importcedr.ciselnikmmrgrantoveschemav01;
create view importcedr.v_opatreni as select idopatreni as id, opatrenikod as kod, opatreninazev as nazev from importcedr.ciselnikcedropatreniv01 union select idopatreni as id, opatrenikod as kod, opatreninazev as nazev from importcedr.ciselnikmmropatreniv01;
create view importcedr.v_podopatreni as select idpodopatreni as id, podopatrenikod as kod, podopatreninazev as nazev from importcedr.ciselnikcedrpodopatreniv01 union select idpodopatreni as id, podopatrenikod as kod, podopatreninazev as nazev from importcedr.ciselnikmmrpodopatreniv01;
create view importcedr.v_podprogram as select idpodprogram as id, podprogramkod as kod, podprogramnazev as nazev from importcedr.ciselnikcedrpodprogramv01 union select idpodprogram as id, podprogramkod as kod, podprogramnazev as nazev from importcedr.ciselnikmmrpodprogramv01;
create view importcedr.v_adresa as select uni.idprijemce, uni.obecnazev, ok.okresnazev, uni.psc from (select idprijemce, obecnazev, iriobec, psc from importcedr.adresasidlo union select idprijemce, obecnazev, obec as iriobec, null as psc from importcedr.adresabydliste) uni left join importcedr.ciselnikobecv01 ob on uni.iriobec = ob.id left join (select distinct on (trim(trailing '/' from substring(id from '^.+/'))) trim(trailing '/' from substring(id from '^.+/')) as nid, okresnazev from importcedr.ciselnikokresv01) ok on ok.nid = ob.okresnad;
create materialized view importcedr.mv_dotace as select dot.iddotace, dot.podpisdatum datumpodpisu, dot.projektnazev nazevprojektu, dot.projektidnetifikator idprojektu,  dot.projektkod kodprojektu, dot.dtaktualizace datumaktualizace, pri.obchodnijmeno prijemceobchodnijmeno,  pri.jmeno || ' ' || pri.prijmeni prijemcejmeno, pri.ico prijemceico, pri.roknarozeni prijemceroknarozeni, adr.obecnazev prijemceobec, adr.okresnazev prijemceokres, adr.psc prijemcepsc, COALESCE(pro.programnazev, opr.nazev, opa.nazev, grs.nazev) programnazev,  COALESCE(pro.programkod, opr.kod, opa.kod, grs.kod) programkod, 'http://cedropendata.mfcr.cz/c3lod/cedr/resource/Dotace/'|| dot.iddotace as urlzdroje, 'cedr' as nazevzdroje, md5(ROW(dot.iddotace, dot.podpisdatum, dot.projektnazev, dot.projektidnetifikator,  dot.projektkod, dot.dtaktualizace, pri.obchodnijmeno,  pri.jmeno || ' ' || pri.prijmeni, pri.ico, pri.roknarozeni, adr.obecnazev, adr.okresnazev, adr.psc, COALESCE(pro.programnazev, opr.nazev, opa.nazev, grs.nazev),  COALESCE(pro.programkod, opr.kod, opa.kod, grs.kod))::TEXT) as hash from importcedr.dotace dot left join importcedr.prijemcepomoci pri on pri.idprijemce = dot.idprijemce left join importcedr.v_adresa adr on pri.idprijemce = adr.idprijemce left join importcedr.ciselnikprogramv01 pro on dot.iriprogram = pro.id left join importcedr.v_operacniprogram opr on dot.irioperacniprogram = opr.id left join importcedr.v_opatreni opa on dot.iriopatreni = opa.id left join importcedr.v_grantoveschema grs on dot.irigrantoveschema = grs.id;
create materialized view importcedr.mv_rozhodnuti as select roz.iddotace, roz.idrozhodnuti id, roz.castkapozadovana, roz.castkarozhodnuta, roz.rokrozhodnuti rok, roz.navratnostindikator jepujcka, fzd.financnizdrojnazev zdrojfinanci, pos.dotaceposkytovatelnazev poskytovatel, 'cedr' as nazevzdroje, md5(ROW(roz.iddotace, roz.idrozhodnuti, roz.castkapozadovana, roz.castkarozhodnuta, roz.rokrozhodnuti, roz.navratnostindikator, fzd.financnizdrojnazev, pos.dotaceposkytovatelnazev)::TEXT) as hash from importcedr.rozhodnuti roz left join importcedr.ciselnikfinancnizdrojv01 fzd on roz.irifinancnizdroj = fzd.id left join importcedr.ciselnikdotaceposkytovatelv01 pos on roz.iriposkytovateldotace = pos.id where roz.refundaceindikator = 'false';
create materialized view importcedr.mv_cerpani as select obd.idrozhodnuti, obd.idobdobi id, obd.castkaspotrebovana, obd.rozpoctoveobdobi rok, 'cedr' as nazevzdroje, md5(ROW(obd.idrozhodnuti, obd.idobdobi, obd.castkaspotrebovana, obd.rozpoctoveobdobi)::TEXT) as hash from importcedr.rozpoctoveobdobi obd;

