drop materialized view cedr.mv_cerpani;
drop materialized view cedr.mv_rozhodnuti;
drop materialized view cedr.mv_dotace;
drop view cedr.v_operacniprogram;
drop view cedr.v_priorita;
drop view cedr.v_grantoveschema;
drop view cedr.v_opatreni;
drop view cedr.v_podopatreni;
drop view cedr.v_podprogram;
drop view cedr.v_adresa;